### ISSUE TITLE
panic问题解除

### ISSUE THREAD

**Issue by MaurUppi** [88250/city-geo#5]
### 描述问题 Describe the problem

```shell
2024/01/07 23:02:07 city [苏州市] result failed [[Get "http://api.map.baidu.com/geocoding/v3/?address=%E6%B1%9F%E8%8B%8F%E7%9C%81%E8%8B%8F%E5%B7%9E%E5%B8%82%E5%90%B4%E6%B1%9F%E5%8C%BA&ak=&output=json": EOF]]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0xd25666]

goroutine 1 [running]:
main.query({0xc00045cc46?, 0x24?}, {0xc00045cc4d?, 0x1?}, {0xc00045cc57, 0x9}, {0xc00045cc61?, 0x9?})
        D:/Github/city-geo/main.go:76 +0x526
main.main()
        D:/Github/city-geo/main.go:46 +0x1d7

```

**Comment by MaurUppi** [comment]
非常感谢提供
